import http from 'k6/http';

export function Register(cid) {
    const customerID = `${__VU}${__ITER}${cid}`;
    const url = 'https://www.thai-ran.com/';
    const headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6ImVpZWkiLCJpYXQiOjE3MDkxNzcxOTV9.wiAusPxPuvLKtcM_Hgbx3agchQEvIAN-VpuY8rce8pI',
    };
    const data = {
        CustomerID: customerID,
        recruitment_unit_id: "11",
        recruitment_unit: "บช.ตชด.",
        regis_type_id: "1",
        regis_type: "นสต.",
        location_id: "11",
        name1: "นาย",
        name2: "ทดสอบ11",
        name3: "ทดสอบ11",
        gender: "ชาย",
        national: "ไทย",
        race: "ไทย",
        religion: "พุทธ",
        birthdate: "11-11-2541",
        age_year: "25",
        age_month: "8",
        height: "199",
        weight: "80",
        chest: "96",
        soldier_check_2: "สด.8",
        extra_point_value: "1",
        extra_parent: "นายคะแนน พิเศษ",
        extra_parent_cause: "ได้รับบาดเจ็บสาหัส",
        degree_position: "วุฒิ ม.6 หรือปริญญาบัตรวิชาชีพ ปวช. หรือเทียบเท่า",
        university: "มหาวิทยาลัยธรรมศาสตร์",
        university_from: "ปทุมธานี",
        graduate_date: "10-4-2560",
        gpa: "3.55",
        sms_status: "1",
        sms_mobile: "0848652222",
        sms_email: "smstest@test.com",
        address: "888",
        moo: "2",
        village: "เมืองทอง",
        soi: "6",
        road: "พุทธา",
        sub_district: "ในเมือง",
        district: "เมือง",
        province: "ขอนแก่น",
        zipcode: "40000",
        telephone: "0-2283-4000",
        telephone_con: "04",
        telmobile: "087-445-1547",
        email: "jojoji@test.com",
        emer_prefix: "นาย",
        emer_firstname: "ฉุกเฉิน1",
        emer_lastname: "ฉุกเฉิน1",
        emer_address: "22",
        emer_moo: "9",
        emer_village: "นะโม",
        emer_soi: "15",
        emer_road: "ปิ่นเอก",
        emer_sub_district: "นายูง",
        emer_district: "นายูง",
        emer_province: "อุดรธานี",
        emer_zipcode: "41380",
        emer_telmobile: "084-149-2210",
        emer_telephone: "0-2283-4000",
        emer_telephone_con: "04",
        emer_email: "emerzz@test.com",
        file_img: "1350100462583_fileImg.jpeg",
        file_id_card: "1350100462583_fileIdCard.jpeg",
        ip: "::1"
    };
    const res = http.post(url, JSON.stringify(data), { headers: headers });
    return res;
}
